import { Component } from '@angular/core';

@Component({
  selector: 'app-terms',
  standalone: true,
  template: `
    <div style="max-width: 800px; margin: 0 auto; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6;">
      <h1>Terms of Service</h1>
      <p><strong>Last updated:</strong> May 2026</p>

      <h2>1. Acceptance of Terms</h2>
      <p>By using TradeAsk, you agree to these Terms of Service. If you do not agree, do not use the service.</p>

      <h2>2. Service Description</h2>
      <p>TradeAsk provides AI-assisted answers to construction and trade compliance questions, reviewed by industry professionals. The service is provided "as is" for informational purposes only.</p>

      <h2>3. User Responsibilities</h2>
      <ul>
        <li>You must provide accurate information when submitting questions</li>
        <li>You must not use the service for any illegal purpose</li>
        <li>You are responsible for verifying all answers with a licensed professional before acting on them</li>
        <li>You must not submit content that infringes on intellectual property rights</li>
      </ul>

      <h2>4. Disclaimer of Professional Advice</h2>
      <p><strong>TradeAsk does NOT provide professional engineering, architectural, or legal advice.</strong> All answers are for informational purposes only. You must always consult with a licensed professional and your local Authority Having Jurisdiction (AHJ) before making compliance decisions.</p>

      <h2>5. Limitation of Liability</h2>
      <p>TradeAsk and its operators shall not be liable for any damages, injuries, code violations, fines, or losses arising from the use of information provided through this service. Use at your own risk.</p>

      <h2>6. Intellectual Property</h2>
      <p>Questions you submit remain yours. Answers generated by our system are provided for your personal use. You may not redistribute answers commercially without permission.</p>

      <h2>7. Account Termination</h2>
      <p>We reserve the right to terminate accounts that violate these terms or abuse the service.</p>

      <h2>8. Changes to Terms</h2>
      <p>We may update these terms at any time. Continued use of the service constitutes acceptance of updated terms.</p>

      <h2>9. Contact</h2>
      <p>Questions about these terms: <strong>legal&#64;tradeask.app</strong></p>
    </div>
  `,
})
export class Terms {}
