import { Component } from '@angular/core';

@Component({
  selector: 'app-disclaimer',
  standalone: true,
  template: `
    <div style="max-width: 800px; margin: 0 auto; padding: 40px 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; line-height: 1.6;">
      <h1>Construction Compliance Disclaimer</h1>
      <p><strong>Last updated:</strong> May 2026</p>

      <div style="background: #fef3c7; border: 1px solid #f59e0b; border-radius: 8px; padding: 20px; margin: 24px 0;">
        <h2 style="color: #92400e; margin-top: 0;">Important Notice</h2>
        <p style="font-size: 16px; font-weight: 500; color: #92400e;">
          TradeAsk is an informational tool only. It does NOT replace professional inspections,
          licensed contractors, engineers, or your local Authority Having Jurisdiction (AHJ).
        </p>
      </div>

      <h2>Not Professional Advice</h2>
      <p>The answers provided by TradeAsk — whether generated by AI, reviewed by professionals, or sourced from our knowledge base — are <strong>for informational purposes only</strong> and do not constitute professional engineering, architectural, electrical, plumbing, or legal advice.</p>

      <h2>Verify Before Acting</h2>
      <p>Before making any decisions based on information from TradeAsk, you MUST:</p>
      <ul>
        <li>Consult with a licensed professional in the relevant trade</li>
        <li>Verify requirements with your local Authority Having Jurisdiction (AHJ)</li>
        <li>Check that the code edition cited is the one adopted in your jurisdiction</li>
        <li>Consider site-specific conditions that may affect compliance requirements</li>
      </ul>

      <h2>Jurisdiction Varies</h2>
      <p>Building codes, electrical codes (NEC), plumbing codes (IPC/UPC), and safety regulations (OSHA) are adopted at the state and local level. Your jurisdiction may use a different edition or have local amendments that override national model codes. TradeAsk answers reference national model codes and may not reflect your specific local requirements.</p>

      <h2>No Liability</h2>
      <p>TradeAsk, its operators, contributors, and AI systems accept NO LIABILITY for:</p>
      <ul>
        <li>Code violations or failed inspections</li>
        <li>Property damage or personal injury</li>
        <li>Fines, penalties, or legal action</li>
        <li>Any loss arising from reliance on information provided</li>
      </ul>

      <h2>AI Limitations</h2>
      <p>Our AI system can make errors. While we have expert review processes, no system is infallible. Always exercise professional judgment and verify critical compliance decisions independently.</p>

      <p style="margin-top: 32px; font-style: italic; color: #6b7280;">
        By using TradeAsk, you acknowledge that you have read and understood this disclaimer.
      </p>
    </div>
  `,
})
export class Disclaimer {}
